version: "3.8"

services:
  payment-service:
    build:
      context: ./app/payment-service
      dockerfile: Dockerfile
    ports:
      - "34000:3000"
      - "9229:9229"
    volumes:
      - ./app/payment-service:/app
      - /app/node_modules
    networks:
      payment-service-gex-net

networks:
  payment-service-gex-net:
